"use client";

import { useCallback, useEffect, useRef, useState, type CSSProperties, type PointerEvent } from "react";
import "./LineSidebar.css";

type Falloff = "linear" | "smooth" | "sharp";
type LineSidebarProps = { items: string[]; accentColor?: string; textColor?: string; markerColor?: string; showIndex?: boolean; showMarker?: boolean; proximityRadius?: number; maxShift?: number; falloff?: Falloff; markerLength?: number; markerGap?: number; tickScale?: number; scaleTick?: boolean; itemGap?: number; fontSize?: number; smoothing?: number; defaultActive?: number | null; onItemClick?: (index: number, label: string) => void; className?: string };
const FALLOFF_CURVES: Record<Falloff, (progress: number) => number> = { linear: p => p, smooth: p => p * p * (3 - 2 * p), sharp: p => p * p * p };

export default function LineSidebar({ items, accentColor = "#A855F7", textColor = "#c4c4c4", markerColor = "#6c6c6c", showIndex = true, showMarker = true, proximityRadius = 100, maxShift = 30, falloff = "smooth", markerLength = 60, markerGap = 0, tickScale = .5, scaleTick = true, itemGap = 20, fontSize = 1.1, smoothing = 100, defaultActive = null, onItemClick, className = "" }: LineSidebarProps) {
  const listRef = useRef<HTMLUListElement>(null); const itemRefs = useRef<Array<HTMLLIElement | null>>([]); const targetsRef = useRef<number[]>([]); const currentRef = useRef<number[]>([]); const rafRef = useRef<number | null>(null); const lastRef = useRef(0); const activeRef = useRef(defaultActive); const [activeIndex, setActiveIndex] = useState(defaultActive);
  activeRef.current = activeIndex;
  const runFrame = useCallback((now: number) => { const dt = Math.min((now - lastRef.current) / 1000, .05); lastRef.current = now; const k = 1 - Math.exp(-dt / (Math.max(smoothing, 1) / 1000)); let moving = false; itemRefs.current.forEach((element, index) => { if (!element) return; const target = Math.max(targetsRef.current[index] || 0, activeRef.current === index ? 1 : 0); const current = currentRef.current[index] || 0; const next = current + (target - current) * k; const settled = Math.abs(target - next) < .0015; const value = settled ? target : next; currentRef.current[index] = value; element.style.setProperty("--effect", value.toFixed(4)); if (!settled) moving = true; }); rafRef.current = moving ? requestAnimationFrame(runFrame) : null; }, [smoothing]);
  const startLoop = useCallback(() => { if (rafRef.current !== null) return; lastRef.current = performance.now(); rafRef.current = requestAnimationFrame(runFrame); }, [runFrame]);
  const handlePointerMove = useCallback((event: PointerEvent<HTMLUListElement>) => { const list = listRef.current; if (!list) return; const pointerY = event.clientY - list.getBoundingClientRect().top; const ease = FALLOFF_CURVES[falloff]; targetsRef.current = itemRefs.current.map(element => { if (!element) return 0; const distance = Math.abs(pointerY - (element.offsetTop + element.offsetHeight / 2)); return ease(Math.max(0, 1 - distance / proximityRadius)); }); startLoop(); }, [falloff, proximityRadius, startLoop]);
  const handlePointerLeave = useCallback(() => { targetsRef.current = targetsRef.current.map(() => 0); startLoop(); }, [startLoop]);
  useEffect(() => { startLoop(); return () => { if (rafRef.current !== null) cancelAnimationFrame(rafRef.current); }; }, [activeIndex, startLoop]);
  const style = { "--accent-color": accentColor, "--text-color": textColor, "--marker-color": markerColor, "--marker-length": `${markerLength}px`, "--marker-gap": `${markerGap}px`, "--tick-scale": tickScale, "--max-shift": `${maxShift}px`, "--item-gap": `${itemGap}px`, "--font-size": `${fontSize}rem`, "--smoothing": `${smoothing}ms` } as CSSProperties;
  return <nav className={`line-sidebar${showMarker ? " line-sidebar--markers" : ""}${scaleTick ? " line-sidebar--scale-tick" : ""}${className ? ` ${className}` : ""}`} style={style} aria-label="Chapters"><ul ref={listRef} className="line-sidebar__list" onPointerMove={handlePointerMove} onPointerLeave={handlePointerLeave}>{items.map((label, index) => <li key={`${label}-${index}`} ref={element => { itemRefs.current[index] = element; }} className="line-sidebar__item" aria-current={activeIndex === index ? "true" : undefined} onClick={() => { setActiveIndex(index); onItemClick?.(index, label); }}>{showMarker && <span className="line-sidebar__marker" aria-hidden="true" />}<span className="line-sidebar__label">{showIndex && <span className="line-sidebar__index">{String(index + 1).padStart(2, "0")}</span>}<span className="line-sidebar__text">{label}</span></span></li>)}</ul></nav>;
}
